package com.myspace.vendormanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class unit1 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean isKPIReportable;

	public unit1() {
	}

	public java.lang.Boolean getIsKPIReportable() {
		return this.isKPIReportable;
	}

	public void setIsKPIReportable(java.lang.Boolean isKPIReportable) {
		this.isKPIReportable = isKPIReportable;
	}

	public unit1(java.lang.Boolean isKPIReportable) {
		this.isKPIReportable = isKPIReportable;
	}

}