package com.myspace.vendormanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Vendor implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String address;
	private java.lang.String details;
	private java.lang.String name;
	private java.lang.String phoneNumber;
	private java.lang.String vendorNumber;
	public Vendor() {
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getDetails() {
		return this.details;
	}

	public void setDetails(java.lang.String details) {
		this.details = details;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(java.lang.String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public java.lang.String getVendorNumber() {
		return this.vendorNumber;
	}

	public void setVendorNumber(java.lang.String vendorNumber) {
		this.vendorNumber = vendorNumber;
	}

	public Vendor(java.lang.String address, java.lang.String details,
			java.lang.String name, java.lang.String phoneNumber,
			java.lang.String vendorNumber) {
		this.address = address;
		this.details = details;
		this.name = name;
		this.phoneNumber = phoneNumber;
		this.vendorNumber = vendorNumber;
	}

}